<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ListadoTurnos.aspx.cs" Inherits="TP_INT_P2.ListadoTurnos" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server" >
        <h2>Listado de Turnos</h2>
    <p>
        Médico legajo: <asp:Label ID="lblLegajo" runat="server" Text=""></asp:Label>
    </p>
<asp:Panel ID="Panel1" runat="server" CssClass="mx-auto w-75 border p-3">
    <asp:GridView ID="gvTurnos" runat="server"
            AutoGenerateColumns="False" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            AutoGenerateSelectButton="True"
            CellPadding="10" 
            CellSpacing="5"
            GridLines="None" 
            OnRowDeleting="gvTurnos_RowDeleting" 
            OnRowCancelingEdit="gvTurnos_RowCancelingEdit"
            OnRowEditing="gvTurnos_RowEditing" 
            OnRowUpdating="gvTurnos_RowUpdating" 
            AllowPaging="True" 
            OnPageIndexChanging="gvTurnos_PageIndexChanging"
            Width="100%"
        
        >
            <EmptyDataTemplate>
                <div class="container mt-3">
                    <div class="alert alert-warning text-center" role="alert">
                        No se encontraron datos para mostrar.
                    </div>
                </div>
            </EmptyDataTemplate>
            <Columns>

                <asp:TemplateField HeaderText="Fecha">
                    <EditItemTemplate>
                        <asp:Label ID="lbl_eit_Fecha" runat="server" Text='<%# Eval("fecha_T", "{0:dd/MM/yyyy HH:mm}") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lbl_it_Fecha" runat="server"  Text='<%# Eval("fecha_T", "{0:dd/MM/yyyy HH:mm}") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Médico">
                    <EditItemTemplate>
                        <asp:Label ID="lbl_eit_FullNameMedico" runat="server" Text='<%# Eval("fullNameMedico") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lbl_it_FullNameMedico" runat="server" Text='<%# Eval("fullNameMedico") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                
                <asp:TemplateField HeaderText="DNI">
                    <EditItemTemplate>
                        <asp:Label ID="lbl_eit_DNI" runat="server" Text='<%# Eval("dni_T") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lbl_it_DNI" runat="server" Text='<%# Eval("dni_P") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Nombre">
                    <EditItemTemplate>
                        <asp:Label ID="tb_eit_Nombre" runat="server" Text='<%# Eval("nombre_P") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lbl_it_Nombre" runat="server" Text='<%# Eval("nombre_P") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Apellido">
                    <EditItemTemplate>
                        <asp:Label ID="tb_eit_Apellido" runat="server" Text='<%# Eval("apellido_P") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lbl_it_Apellido" runat="server" Text='<%# Eval("apellido_P") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Email">
                    <EditItemTemplate>
                        <asp:Label ID="tb_eit_Email" runat="server" Text='<%# Eval("email_P") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lbl_it_Email" runat="server" Text='<%# Eval("email_P") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Teléfono">
                    <EditItemTemplate>
                        <asp:Label ID="tb_eit_Telefono" runat="server" Text='<%# Eval("telefono_P") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lbl_it_Telefono" runat="server" Text='<%# Eval("telefono_P") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Asistencia">
                    <EditItemTemplate>
                        <asp:CheckBox ID="chb_eit_Asistencia" runat="server" Checked='<%# Bind("asistencia_T") %>'></asp:CheckBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:CheckBox ID="chb_it_Asistencia" runat="server"  Enabled="false" Checked='<%# Convert.ToBoolean(Eval("asistencia_T")) %>'></asp:CheckBox>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Observación">
                    <EditItemTemplate>
                        <asp:TextBox ID="tb_eit_Observacion" runat="server" Text='<%# Bind("observacion_T") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lbl_it_Observacion" runat="server" Text='<%# Eval("observacion_T") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>



                <asp:TemplateField HeaderText="Cancelado">
                    <EditItemTemplate>
                        <asp:CheckBox ID="chb_eit_Cancelado" runat="server" Checked='<%# Bind("cancelado_T") %>'></asp:CheckBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:CheckBox ID="lbl_it_Cancelado" runat="server"  Enabled="false" Checked='<%# Convert.ToBoolean(Eval("cancelado_T")) %>'></asp:CheckBox>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Legajo" ItemStyle-CssClass="d-none" HeaderStyle-CssClass="d-none">
                    <ItemTemplate>
                        <asp:HiddenField ID="hfLegajo" runat="server" Value='<%# Eval("legajo_T") %>' />
                    </ItemTemplate>
                </asp:TemplateField>

            </Columns>
            </asp:GridView>
 </asp:Panel>
            <script>
        $(document).ready(function () {
            $('.datepicker').datepicker({
                format: 'yyyy-mm-dd',
                autoclose: true,
                todayHighlight: true
            });
        });
            </script>
    </asp:Content>




